feeds:
  - name: Bad Astronomy
    url: http://www.slate.com/blogs/bad_astronomy.fulltext.all.rss
  - name: Whatever
    url: http://whatever.scalzi.com/feed
  - name: Justine Larbalestier
    url: http://justinelarbalestier.com/blog/feed/
  - name: Mary Robinette Kowal
    url: http://maryrobinettekowal.com/category/journal/feed
  - name: Pharyngula
    url: http://freethoughtblogs.com/pharyngula/feed/
  - name: Neurologica
    url: http://theness.com/neurologicablog/index.php/feed/
  - name: Greta Christina's Blog
    url: http://the-orbit.net/greta/feed/
  - name: Lousy Canuck
    url: http://the-orbit.net/lousycanuck/feed/
  - name: Dietitian at Home
    url: http://dietitianathome.wordpress.com/feed/
  - name: Winnipeg Skeptics Blog
    url: http://winnipegskeptics.com/feed/
  - name: xkcd
    url: http://xkcd.com/rss.xml
  - name: Wondermark
    url: http://feeds.feedburner.com/wondermark
  - name: Boing Boing
    url: http://boingboing.net/feed

keys:
  open: ' '
  prev_item: K
  next_item: J
  prev_feed: H
  next_feed: L
  scroll_up: KEY_UP
  scroll_down: KEY_DOWN
  toggle_read: R
  toggle_star: S
  open_in_browser: O
  quit: Q

database: ~/.tread.db
browser: html2text
retries: 10
timeout: 10
refresh: 10
ascii_images: true
buffer_lines: 1000
unread_count: true
