feeds:
  - http://whatever.scalzi.com/feed
  - http://freethoughtblogs.com/pharyngula/feed/
  - http://the-orbit.net/greta/feed/
  - http://the-orbit.net/lousycanuck/feed/
  - http://dietitianathome.wordpress.com/feed/
  - http://winnipegskeptics.com/feed/
  - http://xkcd.com/rss.xml
  - http://boingboing.net/feed
  - http://feeds.feedburner.com/wondermark

keys:
  prev_item: K
  next_item: J
  prev_feed: H
  next_feed: L
  scroll_up: KEY_UP
  scroll_down: KEY_DOWN
  mark_read: R
  mark_unread: U
  star: S
  open_in_browser: O
  quit: Q

retries: 10
timeout: 10
refresh: 10
browser: lynx
ascii_images: true
buffer_lines: 1000
