feeds:
  - http://freethoughtblogs.com/pharyngula/feed/
  - http://xkcd.com/rss.xml
  - http://boingboing.net/feed

retries: 10
timeout: 10
browser: lynx
ascii_images: true
buffer_lines: 1000
title: TREAD
