feeds:
  - http://freethoughtblogs.com/pharyngula/feed/
  - http://xkcd.com/rss.xml
  - http://boingboing.net/feed

keys:
  next_item: J
  prev_item: K
  next_feed: L
  prev_feed: H
  scroll_down: KEY_DOWN
  scroll_up: KEY_UP
  open_in_browser: O
  mark_read: R
  mark_unread: U
  star: S
  quit: Q

retries: 10
timeout: 10
browser: lynx
ascii_images: true
buffer_lines: 1000
title: TREAD
