feeds:
  - name: Whatever
    url: http://whatever.scalzi.com/feed
  - name: Pharyngula
    url: http://freethoughtblogs.com/pharyngula/feed/
  - name: Greta Christina's Blog
    url: http://the-orbit.net/greta/feed/
  - name: Lousy Canuck
    url: http://the-orbit.net/lousycanuck/feed/
  - name: Dietitian at Home
    url: http://dietitianathome.wordpress.com/feed/
  - name: Winnipeg Skeptics Blog
    url: http://winnipegskeptics.com/feed/
  - name: xkcd
    url: http://xkcd.com/rss.xml
  - name: Wondermark
    url: http://feeds.feedburner.com/wondermark
  - name: Boing Boing
    url: http://boingboing.net/feed

keys:
  prev_item: K
  next_item: J
  prev_feed: H
  next_feed: L
  scroll_up: KEY_UP
  scroll_down: KEY_DOWN
  mark_read: R
  mark_unread: U
  star: S
  open_in_browser: O
  quit: Q

database: ~/.tread.db
browser: lynx
retries: 10
timeout: 10
refresh: 10
ascii_images: true
buffer_lines: 1000
